#!/usr/bin/env bash

GVM_HOME=$HOME/.gvm
GVM_CURRENT_FILE=${GVM_HOME}/ghc-current
GVM_PATHS_FILE=${GVM_HOME}/ghc-paths

GHC_DEFAULT_VERSION=system
GHC_VERSIONS=(system)

GHC_DIRS=$HOME/Software
GHC_SYSTEM=/usr/bin

get_avail_ghcs() {
	local ghc_dirs=$( cat ${GVM_PATHS_FILE} | grep "^dir," | sed "s/^dir,//")
	GHC_PATHS=${ghc_dirs}
}

get_ghc_versions() {
	get_avail_ghcs
   local d=""

	for p in ${GHC_PATHS[@]}
	do 
		pushd ${p} > /dev/null
		d=$(ls */bin/ghc | sed "s/\/.*//")
		popd > /dev/null
	done

	# local soft=$(ls ${GHC_DIRS} | grep "^ghc-" | sed "s/^ghc-//")
	GHC_VERSIONS=(system ${d})
}

get_ghc_version() {
	if [ -n "${GVM}" ]; then
		GHC_VERSION=${GVM}
	elif [ -z "${GHC_VERSION}" ]; then
		GHC_VERSION=${GHC_DEFAULT_VERSION}
		GHC_VERSION=`cat ${GVM_CURRENT_FILE} | head -1`
	fi
}

list_ghc_versions() {
	get_ghc_versions
	get_ghc_version
	echo "GHC Versions:"; echo
	for v in ${GHC_VERSIONS[@]}
	do
		local arch=$( run_ghc_version ${v} ghc '--info' | grep "Target platform" | cut -d, -f3 | sed "s/[\"\)]//g")
		local vers=$( run_ghc_version ${v} ghc '--info' | grep "Project version" | cut -d, -f3 | sed "s/[\"\)]//g")
		if [ "${GHC_VERSION}" = "${v}" ]; then
			printf "=> %-12s %-18s %s\n" ${v} "[${vers}]" "[${arch}]"
		else
			printf "   %-12s %-18s %s\n" ${v} "[${vers}]" "[${arch}]"
		fi
	done
	echo
}

set_ghc_version() {
	get_ghc_versions
	ver=$1
	nov=1
	for v in ${GHC_VERSIONS[@]}
	do
		if [ "${ver}" = "$v" ]; then
			nov=0
		elif [ "${ver}" = "ghc-$v" ]; then
			nov=0
			ver=${v}
		fi
	done
	if [ "${nov}" = "1" ]; then
		echo "ERROR: Not  aware of such a GHC version: ${ver}"
	else
		echo "${ver}" > ${GVM_CURRENT_FILE}
		echo "Using ghc-${ver}"
	fi
}

run_ghc_program() {
	get_ghc_version
	run_ghc_version ${GHC_VERSION} $@
}

run_ghc_version() {
	local ver=$1
	local prog=$2
	shift 2
	local args=$@
	
	if [ "$ver" = "system" ]; then
		${GHC_SYSTEM}/${prog} ${args}
	else
		${GHC_DIRS}/${ver}/bin/${prog} ${args} ${GVM_OPTS}
	fi
}

