#!/usr/bin/env bash
# ghctest - GHC test help

function ghctest() {
	if [[ -e './Makefile' ]]; then
		T=fast
		N=12
		if [[ -n "$1" ]]; then
			T=$1
		fi
		if [[ -n "$2" ]]; then
			N=$2
		fi
		if [[ -n "$3" ]]; then
			FILE=$3
		else
			FILE="$T-log"
		fi
		echo "Running testsuite ($W) with $N threads."
		echo "Saving log to file $FILE."
		echo ""
		echo "============================================================"
		make $T THREADS=$N 2>&1 | tee $FILE
		echo "============================================================"
		echo "Testing ran successfully with $N threads."
		echo "Log saved to file $FILE"
		echo ""
	else
		echo "Error: Testsuite 'Makefile' doesn't exist"
		echo "       You don't seem to be in a GHC build tree!"
	fi
}

ghctest $@

