#!/bin/bash

who=davidt
location=repos

function usage() {
  echo "Usage: [-p] [-a NAME] <market|tezzer> <repo name>"
  echo ""
  echo "    -p       Push current repo to new remote"
  echo "    -a NAME  Add new repo as remote using NAME"
  echo ""
  echo "Sets up a new repo on market to push to."
  exit 1
}

if [ $# -gt 5 -o $# -lt 2 ]; then
  usage
fi

while (( "$#" )); do
  if [ $# -eq 2 ]; then
    remo=$1
    repo=$2
    shift
    shift
  elif [ $1 = "-p" ]; then
    push=y
    shift
  elif [ $1 = "-a" ]; then
    if [ $# -lt 4 ]; then
      usage
    fi
    addr=y
    rname=$2
    shift
    shift
  else
    usage
  fi
done

if [ -z "$repo" -o -z "$remo" ]; then
  usage
fi

if [ "$remo" = "market" ]; then
  remote=market.scs.stanford.edu
elif [ "$remo" = "tezzer" ]; then
  remote=tezzer.scs.stanford.edu
else
  usage
fi

ssh $who@$remote "git init --bare $location/${repo}.git"

if [ "$push" = "y" ]; then
  git push "$who@$remote:$location/${repo}.git" master:master
fi

if [ "$addr" = "y" ]; then
  git remote add "$rname" $who@$remote:$location/${repo}.git
fi

