#!/usr/bin/env zsh
# hub - Github helper script

if [[ $1 == "clone" && $2 != "" ]]; then
	git clone "git@github.com:dterei/$2.git" $3
elif [[ $1 == "repos" ]]; then
	curl -s http://github.com/api/v2/json/repos/show/dterei | python -mjson.tool | grep name
elif [[ $1 == "list" ]]; then
	curl -s http://github.com/api/v2/json/repos/show/dterei | python -mjson.tool
elif [[ $1 == "" || $1 == "-h" || $1 == "--help" ]]; then
	echo "Usage: \tclone <repo>\t -- Clones the repository \
			\n\trepos\t\t -- List my repositories \
			\n\tlist\t\t -- List (detailed) information on all my repositories"
fi

