#!/usr/bin/env bash
# lmf - LLVM file search

if [ -n "$1" ]; then
	find * -regextype posix-extended -regex ".*.(c|h|cpp|td|cxx|inc)" |\
	xargs egrep --color=always "`echo $1 | sed -e 's/ /\\\s\+/'`"
else
	echo "Find all matching LLVM files containing the search term."
	echo "Usage: lmf <keyword>"
fi

