#!/usr/bin/env bash
# pause - nice pause function (equivalent of DOS pause)

if [ -n "${BASH_VERSION}" ]; then
	read -n1 -r -p "Press any key to continue..." key;
	if [ -n "$key" ]; then
		echo "";
	fi
elif [ -n "${ZSH_VERSION}" ]; then
	read -k "?Press any key to continue..." key;
	echo "";
fi

