#!/bin/env bash
#same_files - Check if any files in two directories are the same

if [ $# != 2 ]; then
  echo "$(basename $0) <dir1> <dir2>"
  exit 1
fi

DIR1=$1
DIR2=$2

if [ ! -d "$DIR1" ]; then
  echo "First argument isn't a directory"
  exit 1
elif [ ! -d "$DIR2" ]; then
  echo "Second argument isn't a directory"
  exit 1
fi

for f in "${DIR1}"/*; do
  if [ -f "$f" ]; then
    for g in "${DIR2}"/*; do
      if [ -f "$g" ]; then
        diff -q "$f" "$g" &> /dev/null
        if [ $? == 0 ]; then
          echo "# Files match!"
          echo "file1: $f"
          echo "file2: $g"
          echo ""
        fi
      fi
    done
  fi
done
