#!/usr/bin/env zsh
# sandbox -- Run a command from a cabal sandbox.

local dir=$PWD conf db
while :; do
	conf=$dir/cabal.sandbox.config
	[[ ! -f $conf ]] || break
	if [[ -z $dir ]]; then
		echo "Cannot find cabal.sandbox.config" >&2
		return 1
	fi
	dir=${dir%/*}
done

db=$(sed -ne '/^package-db: */{s///p;q}' "$conf")
if [[ ! -d $db ]]; then
	echo "$db: does not exist"
	return 1
fi

if [[ $# == 0 ]]; then
	echo GHC_PACKAGE_PATH=${db}:
else
	PATH=$(dirname $db)/bin:$PATH
	GHC_PACKAGE_PATH=${db}: "$@"
fi

