#!/usr/bin/env bash
# scf - Source file search

FILE_TYPES="(s|cc|c|h|cmm|l?hs|x|y|pp|cabal|go|goc|rb|php|java|scala|json|xml|yml|py|js)"
FILE_REGEX="[^_].*\.${FILE_TYPES}"

me=`basename $0`

if [ -n "$1" ]; then
  if hash ag 2>/dev/null; then
    ag "$@"
  else
    if [[ "$OSTYPE" =~ "darwin" || "$OSTYPE" =~ "freebsd" ]]; then
      find -E * -regex "${FILE_REGEX}" |\
      grep -v "_darcs" |\
      grep -v "gopath" |\
      xargs egrep --color=always "`echo $1 | sed -e 's/ /\\\s\+/'`"
    else
      find * -regextype posix-extended -regex "${FILE_REGEX}" |\
      grep -v "_darcs" |\
      grep -v "gopath" |\
      xargs egrep --color=always "`echo $1 | sed -e 's/ /\\\s\+/'`"
    fi
  fi
else
  echo "Find all matching source code files containing the search term."
  echo "Usage: $me <keyword>"
fi
