#!/bin/sh

# For black.davidterei.com, sync (pull-in) from all other machines.
# For all other machines, sync (pull-in) from black.davidterei.com.

if [ "$HOSTNAME" = "silver.davidterei.com" ]; then
  echo "Syncing with black.davidterei.com"
  rsync \
    -rtu \
    --progress \
    --exclude=.DS_Store \
    --exclude=iTunes \
    davidt@black.davidterei.com:/home/davidt/Music \
    /Users/davidt/

elif [ "$HOSTNAME" = "black.davidterei.com" ]; then
  echo "Syncing with silver.davidterei.com"
  rsync \
    -rtu \
    --progress \
    --exclude=.DS_Store \
    --exclude=iTunes \
    davidt@silver.davidterei.com:/Users/davidt/Music \
    /home/davidt/

else
  echo "Can only be run from silver.davidterei.com or black.davidterei.com"
  exit 1
fi
