#!/bin/sh

if [ "$HOSTNAME" = "silver.davidterei.com" ]; then
  echo "Syncing with black.davidterei.com"
  rsync \
    -rtu \
    --progress \
    --exclude=.DS_Store \
    --exclude=iTunes \
    davidt@black.davidterei.com:/home/davidt/Music \
    /Users/davidt/

  echo "Syncing with davidt.scs.stanford.edu"
  rsync \
    -rtu \
    --progress \
    --exclude=.DS_Store \
    --exclude=iTunes \
    davidt@davidt.scs.stanford.edu:/mnt/b/Music \
    /Users/davidt/

elif [ "$HOSTNAME" = "black.davidterei.com" ]; then
  echo "Syncing with silver.davidterei.com"
  rsync \
    -rtu \
    --progress \
    --exclude=.DS_Store \
    --exclude=iTunes \
    davidt@silver.davidterei.com:/Users/davidt/Music \
    /home/davidt/

elif [ "$HOSTNAME" = "davidt.scs.stanford.edu" ]; then
  echo "Syncing with silver.davidterei.com"
  rsync \
    -rtu \
    --progress \
    --exclude=.DS_Store \
    --exclude=iTunes \
    davidt@silver.davidterei.com:/Users/davidt/Music \
    /mnt/b/

else
  echo "Can only be run from silver.davidterei.com, black.davidterei.com or"
  echo "davidt.scs.stanford.edu"
  exit 1
fi

