#!/bin/sh
# tmux wrapper to conditionally load tmux-osx.conf on osx.

unset cfg

if [ "$OSTYPE" = "darwin13" ] ; then
	cfg=$HOME/.tmux-osx.conf
	path=/usr/local/bin/tmux
else
	path=/usr/bin/tmux
fi

exec "${path}" ${cfg+-f "$cfg"} "$@"

